# Generated by Django 5.1 on 2024-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата производства"
            ),
        ),
    ]
